# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Joint1:
    has_velocity_limits: true
    max_velocity: 0.98
    has_acceleration_limits: true
    max_acceleration: 1.96
  Joint2:
    has_velocity_limits: true
    max_velocity: 0.98
    has_acceleration_limits: true
    max_acceleration: 1.96
  Joint3:
    has_velocity_limits: true
    max_velocity: 1.31
    has_acceleration_limits: true
    max_acceleration: 2.61
  Joint4:
    has_velocity_limits: true
    max_velocity: 1.31
    has_acceleration_limits: true
    max_acceleration: 2.61
  Joint5:
    has_velocity_limits: true
    max_velocity: 1.31
    has_acceleration_limits: true
    max_acceleration: 2.61
  Joint6:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 3.14
  Joint7:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 3.14
  left_gripper_Joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_Joint:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: false
    max_acceleration: 0
